@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZTc4NzBhYTgxNjZlMDI5ZjQ0MTVlYTEiLCJpYXQiOjE1ODUwMzkxMjd9.q-JnGhhjK4A5O9Lw2OLq26_4Uy7PEJVLOe-4tiDs12M

###
POST http://{{host}}/signup HTTP/1.1
content-type: application/json

{
    "email": "test",
    "password": "test"
}

###
GET http://{{host}}/tracks HTTP/1.1
Authorization: Bearer {{token}}

###
POST http://{{host}}/signin HTTP/1.1
content-type: application/json

{
    "email": "test",
    "password": "test"
}
